msgbox  ( "MENSAGEM FOFINHAAA AQUII" ),  vbinformation,  "NOME DA CAIXINHA"
msgbox  ( "MENSAGEM FOFINHAAA AQUII" ),  16,  "NOME DA CAIXINHA"       (ALERTA VERMELHO)
msgbox  ( "MENSAGEM FOFINHAAA AQUII" ),  vbYesNo,  "NOME DA CAIXINHA"
